"2011-11-24": "Thursday November 24 - Thanksgiving Day"
"2011-11-25": "Friday November 25 - Day After Thanksgiving"
"2011-12-26": "Monday December 26 - Christmas Day (in lieu of Sunday December 25)"
"2012-01-02": "Monday January 2 - New Years Holiday (in lieu of Sunday January 1)"
"2012-01-16": "Monday January 16 - Martin Luther King Jr. Day"
"2012-02-20": "Monday February 20 - President's Day"
"2012-05-28": "Monday May 28 - Memorial Day"
"2012-07-04": "Wednesday July 4 - Independence Day"
"2012-09-03": "Monday September 3 - Labor Day"
"2012-10-08": "Monday October 8 - Columbus Day"
"2012-11-22": "Thursday November 22 - Thanksgiving Day"
"2012-12-23": "Friday November 23 - Day After Thanksgiving"
"2012-12-25": "Tuesday December 25 - Christmas Day"

